name: pzsp
description: A simple dance app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: 5.0.0
  cupertino_icons: ^1.0.8
  camera_web: ^0.3.5
  camera: ^0.11.1
  video_player: ^2.9.5
  video_player_web: ^2.3.5
  supabase_flutter: ^2.0.0
  image: ^4.0.17
  fl_chart: ^1.0.0
  socket_io_client: ^2.0.3+1
  http: ^0.13.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/videos/my_video.mp4
  #   - assets/videos/short_video.mp4
