name: pzsp
description: A simple dance app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: 5.0.0
  supabase_flutter: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
